### ISSUE TITLE
Mandatory Username and Password Requirement

### ISSUE THREAD

**Issue by gibbo520** [akamming/homebridge-domoticz-thermostat#2]
First of all, I’d like to say how excited I am about the functionality of this plugin—it works very well and has been a great addition to my system. However, I’ve noticed a small issue that might need attention.
Currently, the plugin requires a username and password to be set, even in cases where they may not be necessary for the specific use case (localhost is allowed). This can create some friction for users who may not need or want to use these fields in certain configurations.
It would be fantastic if the username and password fields were optional, allowing for a more flexible setup depending on user preferences or system requirements.

I’ve already worked on a possible solution, and Ii like to share the code for it. 
Looking forward to your feedback!

```
let options = {};
        if (this.username && this.password) {
            options = {
                headers: {
                    Authorization: 'Basic ' + btoa(this.username + ':' + this.password),
                }
            };
        }
```

Bye

**Comment by akamming** [comment]
Can’t test it now, but if you leave username and password empty it should work of authentication is switched off..

**Comment by akamming** [comment]
Just tested, works fine for a system without username/password. Just leave it empty
